# Generated by Django 2.0.7 on 2019-06-28 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='daily_Duplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dt', models.DateField(blank=True, null=True)),
                ('trgtq', models.IntegerField(null=True)),
                ('assttyp', models.CharField(max_length=20, null=True)),
                ('revid', models.IntegerField(default=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='daily_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(blank=True, null=True)),
                ('target_quantity', models.IntegerField(null=True)),
                ('asset_subtype', models.CharField(max_length=20, null=True)),
                ('revisionid', models.IntegerField(default=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Duplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fncyr', models.CharField(max_length=20, null=True)),
                ('trgtq', models.IntegerField(null=True)),
                ('assttyp', models.CharField(max_length=20, null=True)),
                ('revid', models.IntegerField(default=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='monthly_Duplicate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fncyr', models.CharField(max_length=20, null=True)),
                ('mnsq', models.CharField(max_length=3, null=True)),
                ('trgtq', models.IntegerField(null=True)),
                ('assttyp', models.CharField(max_length=20, null=True)),
                ('revid', models.IntegerField(default=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='monthly_product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20, null=True)),
                ('month_sequence', models.CharField(max_length=3, null=True)),
                ('target_quantity', models.IntegerField(null=True)),
                ('asset_subtype', models.CharField(max_length=20, null=True)),
                ('revisionid', models.IntegerField(default=99, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20, null=True)),
                ('target_quantity', models.IntegerField(null=True)),
                ('asset_subtype', models.CharField(max_length=20, null=True)),
                ('revisionid', models.IntegerField(default=99, null=True)),
            ],
        ),
    ]
