# Generated by Django 2.0.7 on 2019-08-06 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(max_length=50, null=True)),
                ('navmenu', models.CharField(max_length=50, null=True)),
                ('navitem', models.CharField(max_length=50, null=True)),
                ('navsubitem', models.CharField(max_length=50, null=True)),
                ('link', models.CharField(max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('role', models.CharField(max_length=50, primary_key=True, serialize=False)),
            ],
        ),
        migrations.CreateModel(
            name='testc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, null=True)),
                ('targetone', models.IntegerField(null=True)),
                ('targettwo', models.IntegerField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('emp_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('role', models.CharField(max_length=500, null=True)),
                ('name', models.CharField(max_length=50, null=True)),
                ('designation', models.CharField(max_length=50, null=True)),
                ('department', models.CharField(max_length=50, null=True)),
                ('email', models.CharField(max_length=50, null=True)),
                ('contactno', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
