# Generated by Django 2.0.7 on 2019-07-23 07:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='daily_Duplicate',
        ),
        migrations.DeleteModel(
            name='daily_product',
        ),
        migrations.DeleteModel(
            name='Duplicate',
        ),
        migrations.DeleteModel(
            name='monthly_Duplicate',
        ),
        migrations.DeleteModel(
            name='monthly_product',
        ),
        migrations.DeleteModel(
            name='product',
        ),
    ]
