# Generated by Django 2.0.7 on 2019-09-24 07:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='annualproduction',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=20, null=True)),
                ('target_quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('loco_type', models.CharField(blank=True, max_length=50, null=True)),
                ('buffer_quantity', models.CharField(blank=True, max_length=20, null=True)),
                ('revisionid', models.IntegerField(blank=True, null=True)),
                ('customer', models.CharField(blank=True, max_length=20, null=True)),
            ],
            options={
                'db_table': 'dlw_annual_production',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='jpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(blank=True, max_length=20, null=True)),
                ('revisionid', models.IntegerField(blank=True, null=True)),
                ('jpo', models.CharField(blank=True, max_length=20, null=True)),
                ('subject', models.TextField(blank=True, null=True)),
                ('reference', models.TextField(blank=True, null=True)),
                ('majoralt', models.TextField(blank=True, null=True)),
                ('remark', models.TextField(blank=True, null=True)),
                ('date', models.CharField(blank=True, max_length=30, null=True)),
                ('numyrs', models.CharField(blank=True, max_length=20, null=True)),
                ('numdgp', models.CharField(blank=True, max_length=10, null=True)),
                ('formno', models.TextField(blank=True, null=True)),
                ('headmjr', models.TextField(blank=True, null=True)),
                ('number', models.TextField(blank=True, null=True)),
                ('finalval', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dlw_jpo',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='loconame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loconame', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dlw_loconame',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='materialname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrname', models.TextField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dlw_materialname',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='namedgn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namep', models.CharField(blank=True, max_length=50, null=True)),
                ('design', models.CharField(blank=True, max_length=30, null=True)),
                ('revision', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dlw_namedgn',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(blank=True, max_length=50, null=True)),
                ('navmenu', models.CharField(blank=True, max_length=50, null=True)),
                ('navitem', models.CharField(blank=True, max_length=50, null=True)),
                ('navsubitem', models.CharField(blank=True, max_length=50, null=True)),
                ('link', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dlw_navbar',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Oprn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shop_sec', models.CharField(blank=True, db_column='SHOP_SEC', max_length=10, null=True)),
                ('lc_no', models.CharField(blank=True, db_column='LC_NO', max_length=10, null=True)),
                ('part_no', models.CharField(blank=True, db_column='PART_NO', max_length=10, null=True)),
                ('opn', models.CharField(blank=True, db_column='OPN', max_length=10, null=True)),
                ('des', models.CharField(blank=True, db_column='DES', max_length=4000, null=True)),
                ('pa_hrs', models.DecimalField(blank=True, db_column='PA_HRS', decimal_places=2, max_digits=10, null=True)),
                ('at_hrs', models.DecimalField(blank=True, db_column='AT_HRS', decimal_places=2, max_digits=10, null=True)),
                ('pa', models.DecimalField(blank=True, db_column='PA', decimal_places=2, max_digits=10, null=True)),
                ('at', models.DecimalField(blank=True, db_column='AT', decimal_places=2, max_digits=10, null=True)),
                ('lot', models.DecimalField(blank=True, db_column='LOT', decimal_places=2, max_digits=10, null=True)),
                ('ncp_jbs', models.CharField(blank=True, db_column='NCP_JBS', max_length=5, null=True)),
                ('m5_cd', models.CharField(blank=True, db_column='M5_CD', max_length=5, null=True)),
                ('del_fl', models.CharField(blank=True, db_column='DEL_FL', max_length=5, null=True)),
                ('updt_dt', models.DateField(blank=True, db_column='UPDT_DT', null=True)),
                ('m_1', models.DecimalField(blank=True, db_column='M_1', decimal_places=2, max_digits=5, null=True)),
                ('c_1', models.CharField(blank=True, db_column='C_1', max_length=5, null=True)),
                ('m_2', models.DecimalField(blank=True, db_column='M_2', decimal_places=2, max_digits=5, null=True)),
                ('c_2_field', models.CharField(blank=True, db_column='C_2_', max_length=5, null=True)),
                ('m_3', models.DecimalField(blank=True, db_column='M_3', decimal_places=2, max_digits=5, null=True)),
                ('c_3', models.CharField(blank=True, db_column='C_3', max_length=5, null=True)),
                ('m5_cd_old', models.CharField(blank=True, db_column='M5_CD_OLD', max_length=5, null=True)),
                ('at_old', models.DecimalField(blank=True, db_column='AT_OLD', decimal_places=2, max_digits=6, null=True)),
                ('at310899', models.DecimalField(blank=True, db_column='AT310899', decimal_places=2, max_digits=6, null=True)),
                ('lot310899', models.DecimalField(blank=True, db_column='LOT310899', decimal_places=0, max_digits=2, null=True)),
                ('at_old1', models.DecimalField(blank=True, db_column='AT_OLD1', decimal_places=2, max_digits=6, null=True)),
                ('at_min', models.DecimalField(blank=True, db_column='AT_MIN', decimal_places=0, max_digits=5, null=True)),
                ('at_min_rou', models.DecimalField(blank=True, db_column='AT_MIN_ROU', decimal_places=0, max_digits=5, null=True)),
                ('at011209', models.DecimalField(blank=True, db_column='AT011209', decimal_places=2, max_digits=6, null=True)),
                ('at_hrs1', models.DecimalField(blank=True, db_column='AT_HRS1', decimal_places=2, max_digits=6, null=True)),
                ('lot011209', models.DecimalField(blank=True, db_column='LOT011209', decimal_places=0, max_digits=2, null=True)),
                ('o_at', models.DecimalField(blank=True, db_column='O_AT', decimal_places=2, max_digits=12, null=True)),
                ('o_at_min', models.DecimalField(blank=True, db_column='O_AT_MIN', decimal_places=2, max_digits=12, null=True)),
                ('rmin', models.DecimalField(blank=True, db_column='RMIN', decimal_places=2, max_digits=12, null=True)),
                ('rb', models.DecimalField(blank=True, db_column='RB', decimal_places=2, max_digits=12, null=True)),
                ('rat_hr', models.DecimalField(blank=True, db_column='RAT_HR', decimal_places=2, max_digits=6, null=True)),
                ('rat', models.DecimalField(blank=True, db_column='RAT', decimal_places=2, max_digits=6, null=True)),
                ('mat_rej', models.IntegerField(blank=True, db_column='MAT_REJ', null=True)),
                ('qtr_accep', models.IntegerField(blank=True, db_column='QTR_ACCEP', null=True)),
                ('qty_prod', models.IntegerField(blank=True, db_column='QTY_PROD', null=True)),
                ('work_rej', models.IntegerField(blank=True, db_column='WORK_REJ', null=True)),
            ],
            options={
                'db_table': 'OPRN',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='roles',
            fields=[
                ('role', models.CharField(max_length=50, primary_key=True, serialize=False)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dlw_roles',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(blank=True, max_length=15, null=True)),
                ('shift_id', models.CharField(blank=True, max_length=50, null=True)),
                ('validity_from', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'dlw_shift',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='shift_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(blank=True, max_length=15, null=True)),
                ('shift_id', models.CharField(blank=True, max_length=50, null=True)),
                ('validity_from', models.CharField(blank=True, max_length=30, null=True)),
                ('validity_to', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'dlw_shift_history',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='shop_section',
            fields=[
                ('section_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('section_id', models.CharField(blank=True, max_length=10, null=True)),
                ('section_desc', models.CharField(blank=True, max_length=150, null=True)),
                ('shop_code', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_id', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dlw_shop_section',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='testc',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(blank=True, max_length=20, null=True)),
                ('targetone', models.IntegerField(blank=True, null=True)),
                ('targettwo', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'db_table': 'dlw_testc',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='testing_purpose',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('first', models.CharField(blank=True, max_length=50, null=True)),
                ('second', models.CharField(blank=True, max_length=50, null=True)),
            ],
            options={
                'db_table': 'dlw_testing_purpose',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='user_master',
            fields=[
                ('emp_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('role', models.CharField(blank=True, max_length=500, null=True)),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('designation', models.CharField(blank=True, max_length=50, null=True)),
                ('department', models.CharField(blank=True, max_length=50, null=True)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('contactno', models.CharField(blank=True, max_length=10, null=True)),
                ('parent', models.CharField(blank=True, max_length=50, null=True)),
                ('shop_id', models.CharField(blank=True, max_length=30, null=True)),
            ],
            options={
                'db_table': 'dlw_user_master',
                'managed': False,
            },
        ),
        migrations.AlterModelTable(
            name='tempm14m4',
            table='TEMP_M14M4',
        ),
    ]
