# Generated by Django 2.0.7 on 2019-07-23 07:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('dlw', '0002_auto_20190723_1324'),
    ]

    operations = [
        migrations.CreateModel(
            name='test',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('subject', models.CharField(max_length=20, null=True)),
                ('targetone', models.IntegerField(null=True)),
                ('targettwo', models.IntegerField(null=True)),
            ],
        ),
    ]
