# Generated by Django 2.0.7 on 2019-08-14 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0002_roles_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='parent',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
