# Generated by Django 2.0.7 on 2019-07-23 08:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_test'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='test',
            new_name='testc',
        ),
    ]
