# Generated by Django 2.0.7 on 2019-09-24 07:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_machiningairbox'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='annualproduction',
            options={},
        ),
        migrations.AlterModelOptions(
            name='jpo',
            options={},
        ),
        migrations.AlterModelOptions(
            name='loconame',
            options={},
        ),
        migrations.AlterModelOptions(
            name='materialname',
            options={},
        ),
        migrations.AlterModelOptions(
            name='namedgn',
            options={},
        ),
        migrations.AlterModelOptions(
            name='navbar',
            options={},
        ),
        migrations.AlterModelOptions(
            name='roles',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shift',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shift_history',
            options={},
        ),
        migrations.AlterModelOptions(
            name='shop_section',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testc',
            options={},
        ),
        migrations.AlterModelOptions(
            name='testing_purpose',
            options={},
        ),
        migrations.AlterModelOptions(
            name='user_master',
            options={},
        ),
    ]
