# Generated by Django 2.0.7 on 2019-08-21 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0003_user_master_parent'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift_history',
            fields=[
                ('emp_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('shift_id', models.CharField(max_length=25, null=True)),
                ('validity_from', models.DateField(null=True)),
                ('validity_to', models.DateField(null=True)),
            ],
        ),
        migrations.AddField(
            model_name='user_master',
            name='shift_id',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AddField(
            model_name='user_master',
            name='validity_from',
            field=models.DateField(null=True),
        ),
    ]
