# Generated by Django 2.0.7 on 2019-07-27 08:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_auto_20190723_1407'),
    ]

    operations = [
        migrations.CreateModel(
            name='navbar',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('usertype', models.CharField(max_length=20, null=True)),
                ('navmenu', models.CharField(max_length=20, null=True)),
                ('navitem', models.CharField(max_length=20, null=True)),
                ('navsubitem', models.CharField(max_length=20, null=True)),
            ],
        ),
    ]
