# Generated by Django 2.0.7 on 2019-08-21 14:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_auto_20190821_1904'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shift_history',
        ),
    ]
