# Generated by Django 2.0.7 on 2019-09-24 10:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0004_auto_20190924_1322'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MachiningAirBox',
        ),
        migrations.AlterModelTable(
            name='annualproduction',
            table=None,
        ),
        migrations.AlterModelTable(
            name='jpo',
            table=None,
        ),
        migrations.AlterModelTable(
            name='loconame',
            table=None,
        ),
        migrations.AlterModelTable(
            name='materialname',
            table=None,
        ),
        migrations.AlterModelTable(
            name='namedgn',
            table=None,
        ),
        migrations.AlterModelTable(
            name='navbar',
            table=None,
        ),
        migrations.AlterModelTable(
            name='roles',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shift',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shift_history',
            table=None,
        ),
        migrations.AlterModelTable(
            name='shop_section',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testc',
            table=None,
        ),
        migrations.AlterModelTable(
            name='testing_purpose',
            table=None,
        ),
        migrations.AlterModelTable(
            name='user_master',
            table=None,
        ),
    ]
