# Generated by Django 2.0.7 on 2019-07-27 08:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_navbar'),
    ]

    operations = [
        migrations.AddField(
            model_name='navbar',
            name='link',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
