# Generated by Django 2.0.7 on 2019-08-21 14:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0005_delete_shift_history'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift_history',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=15, null=True)),
                ('shift_id', models.CharField(max_length=25, null=True)),
                ('validity_from', models.DateField(null=True)),
                ('validity_to', models.DateField(null=True)),
            ],
        ),
    ]
