# Generated by Django 2.0.7 on 2019-07-29 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0006_navbar_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='link',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
