# Generated by Django 2.0.7 on 2019-08-21 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0006_shift_history'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_history',
            name='validity_from',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='shift_history',
            name='validity_to',
            field=models.CharField(max_length=25, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='validity_from',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
