# Generated by Django 2.0.7 on 2019-08-22 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0007_auto_20190821_2052'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shift_history',
            name='shift_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='shift_history',
            name='validity_from',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='shift_history',
            name='validity_to',
            field=models.CharField(max_length=30, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='shift_id',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='validity_from',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
