# Generated by Django 2.0.7 on 2019-08-30 08:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0008_auto_20190822_1103'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shift_id', models.CharField(max_length=50, null=True)),
                ('validity_from', models.CharField(max_length=30, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='shift_id',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='validity_from',
        ),
    ]
