# Generated by Django 2.0.7 on 2019-07-31 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0008_auto_20190731_1213'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
