# Generated by Django 2.0.7 on 2019-08-30 08:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0009_auto_20190830_1336'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shift',
        ),
    ]
