# Generated by Django 2.0.7 on 2019-07-31 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0010_remove_user_master_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='created',
            field=models.BooleanField(default=False),
        ),
    ]
