# Generated by Django 2.0.7 on 2019-08-30 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0010_delete_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift',
            fields=[
                ('emp_id', models.CharField(max_length=15, primary_key=True, serialize=False)),
                ('shift_id', models.CharField(max_length=50, null=True)),
                ('validity_from', models.CharField(max_length=30, null=True)),
                ('parent', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=500, null=True)),
            ],
        ),
    ]
