# Generated by Django 2.0.7 on 2019-08-30 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0011_shift'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='shift',
            name='parent',
        ),
        migrations.RemoveField(
            model_name='shift',
            name='role',
        ),
    ]
