# Generated by Django 2.0.7 on 2019-08-30 08:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0012_auto_20190830_1342'),
    ]

    operations = [
        migrations.DeleteModel(
            name='shift',
        ),
    ]
