# Generated by Django 2.0.7 on 2019-07-31 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0012_remove_user_master_created'),
    ]

    operations = [
        migrations.CreateModel(
            name='permissions',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('permission_no', models.IntegerField(null=True)),
                ('role', models.CharField(max_length=25, null=True)),
            ],
        ),
    ]
