# Generated by Django 2.0.7 on 2019-07-31 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0013_permissions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='permissions',
            name='id',
        ),
        migrations.AlterField(
            model_name='permissions',
            name='permission_no',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
