# Generated by Django 2.0.7 on 2019-08-30 08:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0013_delete_shift'),
    ]

    operations = [
        migrations.CreateModel(
            name='shift',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('emp_id', models.CharField(max_length=15, null=True)),
                ('shift_id', models.CharField(max_length=50, null=True)),
                ('validity_from', models.CharField(max_length=30, null=True)),
            ],
        ),
    ]
