# Generated by Django 2.0.7 on 2019-07-31 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0014_auto_20190731_2101'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='permission_no',
            field=models.IntegerField(null=True),
        ),
    ]
