# Generated by Django 2.0.7 on 2019-09-17 09:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0015_auto_20190913_1220'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='navbar',
            table='dlw_navbar',
        ),
        migrations.AlterModelTable(
            name='roles',
            table='dlw_roles',
        ),
        migrations.AlterModelTable(
            name='shift',
            table='dlw_shift',
        ),
        migrations.AlterModelTable(
            name='shift_history',
            table='dlw_shift_history',
        ),
        migrations.AlterModelTable(
            name='testc',
            table='dlw_testc',
        ),
        migrations.AlterModelTable(
            name='user_master',
            table='dlw_user_master',
        ),
    ]
