# Generated by Django 2.0.7 on 2019-07-31 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0015_user_master_permission_no'),
    ]

    operations = [
        migrations.RenameField(
            model_name='permissions',
            old_name='permission_no',
            new_name='permission_id',
        ),
        migrations.RenameField(
            model_name='user_master',
            old_name='permission_no',
            new_name='permission_id',
        ),
    ]
