# Generated by Django 2.0.7 on 2019-09-18 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0016_auto_20190917_1430'),
    ]

    operations = [
        migrations.CreateModel(
            name='shop_section',
            fields=[
                ('section_code', models.CharField(max_length=10, primary_key=True, serialize=False)),
                ('section_id', models.CharField(max_length=10, null=True)),
                ('section_desc', models.CharField(max_length=50, null=True)),
                ('shop_code', models.CharField(max_length=50, null=True)),
                ('shop_id', models.CharField(max_length=50, null=True)),
            ],
        ),
    ]
