# Generated by Django 2.0.7 on 2019-07-31 15:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0016_auto_20190731_2111'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='permissions',
            new_name='permission',
        ),
    ]
