# Generated by Django 2.0.7 on 2019-08-01 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0017_auto_20190731_2117'),
    ]

    operations = [
        migrations.CreateModel(
            name='template_permission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('template_name', models.CharField(max_length=50, null=True)),
                ('role', models.CharField(max_length=50, null=True)),
                ('permission_id', models.IntegerField(null=True)),
            ],
        ),
    ]
