# Generated by Django 2.0.7 on 2019-09-18 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0017_shop_section'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_section',
            name='section_desc',
            field=models.CharField(max_length=150, null=True),
        ),
    ]
