# Generated by Django 2.0.7 on 2019-09-19 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0018_auto_20190918_1611'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='user_master',
            options={},
        ),
    ]
