# Generated by Django 2.0.7 on 2019-08-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0019_navbar_permission_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_permission',
            name='permission_id',
            field=models.CharField(max_length=15, null=True),
        ),
    ]
