# Generated by Django 2.0.7 on 2019-09-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0019_auto_20190919_1222'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_master',
            name='contactno',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='department',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='designation',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='email',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='parent',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='user_master',
            name='role',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterModelTable(
            name='user_master',
            table=None,
        ),
    ]
