# Generated by Django 2.0.7 on 2019-08-01 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0020_auto_20190801_1954'),
    ]

    operations = [
        migrations.AlterField(
            model_name='template_permission',
            name='permission_id',
            field=models.IntegerField(null=True),
        ),
    ]
