# Generated by Django 2.0.7 on 2019-09-19 06:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0020_auto_20190919_1223'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_master',
            name='shop_id',
            field=models.CharField(max_length=30, null=True),
        ),
    ]
