# Generated by Django 2.0.7 on 2019-08-01 15:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0021_auto_20190801_1955'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='navbar',
            name='permission_id',
        ),
    ]
