# Generated by Django 2.0.7 on 2019-09-20 11:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0021_user_master_shop_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='annual_production',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20, null=True)),
                ('target_quantity', models.CharField(max_length=20, null=True)),
                ('loco_type', models.CharField(max_length=50, null=True)),
                ('buffer_quantity', models.CharField(max_length=20, null=True)),
                ('revisionid', models.IntegerField(default=99, null=True)),
                ('customer', models.CharField(default='ind-rail', max_length=20, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='jpo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('financial_year', models.CharField(max_length=20, null=True)),
                ('revisionid', models.IntegerField(default=99, null=True)),
                ('jpo', models.CharField(max_length=20, null=True)),
                ('subject', models.TextField(null=True)),
                ('reference', models.TextField(null=True)),
                ('majoralt', models.TextField(null=True)),
                ('remark', models.TextField(null=True)),
                ('date', models.CharField(max_length=30, null=True)),
                ('numyrs', models.CharField(max_length=20, null=True)),
                ('numdgp', models.CharField(max_length=10, null=True)),
                ('formno', models.TextField(null=True)),
                ('headmjr', models.TextField(null=True)),
                ('number', models.TextField(null=True)),
                ('finalval', models.IntegerField(default=0, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='loconame',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('loconame', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='materialname',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matrname', models.TextField(null=True)),
            ],
        ),
        migrations.CreateModel(
            name='namedgn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('namep', models.CharField(max_length=50, null=True)),
                ('design', models.CharField(max_length=30, null=True)),
                ('revision', models.IntegerField(default=99, null=True)),
            ],
        ),
    ]
