# Generated by Django 2.0.7 on 2019-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0022_remove_navbar_permission_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='roles',
            fields=[
                ('role', models.CharField(max_length=25, primary_key=True, serialize=False)),
            ],
        ),
        migrations.DeleteModel(
            name='permission',
        ),
        migrations.DeleteModel(
            name='template_permission',
        ),
        migrations.RemoveField(
            model_name='user_master',
            name='permission_id',
        ),
    ]
