# Generated by Django 2.0.7 on 2019-08-04 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0023_auto_20190804_1835'),
    ]

    operations = [
        migrations.CreateModel(
            name='flags_table',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('flag_name', models.CharField(max_length=10, null=True)),
                ('flag_value', models.CharField(max_length=10, null=True)),
            ],
        ),
    ]
