# Generated by Django 2.0.7 on 2019-09-23 06:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0023_testing_purpose'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='oprn',
            options={},
        ),
    ]
