# Generated by Django 2.0.7 on 2019-09-23 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0024_auto_20190923_1216'),
    ]

    operations = [
        migrations.AddField(
            model_name='oprn',
            name='mat_rej',
            field=models.IntegerField(blank=True, db_column='MAT_REJ', null=True),
        ),
        migrations.AddField(
            model_name='oprn',
            name='qtr_accep',
            field=models.IntegerField(blank=True, db_column='QTR_ACCEP', null=True),
        ),
        migrations.AddField(
            model_name='oprn',
            name='qty_prod',
            field=models.IntegerField(blank=True, db_column='QTY_PROD', null=True),
        ),
        migrations.AddField(
            model_name='oprn',
            name='work_rej',
            field=models.IntegerField(blank=True, db_column='WORK_REJ', null=True),
        ),
    ]
