# Generated by Django 2.0.7 on 2019-08-04 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0024_flags_table'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flags_table',
            name='flag_name',
            field=models.CharField(max_length=25, null=True),
        ),
    ]
