# Generated by Django 2.0.7 on 2019-09-23 06:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0025_auto_20190923_1157'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='oprn',
            table='OPRN',
        ),
    ]
