# Generated by Django 2.0.7 on 2019-08-05 07:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0025_auto_20190804_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='navbar',
            name='navitem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='navmenu',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='navsubitem',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='navbar',
            name='role',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
