# Generated by Django 2.0.7 on 2019-08-05 07:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dlw', '0026_auto_20190805_1243'),
    ]

    operations = [
        migrations.DeleteModel(
            name='flags_table',
        ),
    ]
